sudo: false
dist: trusty
group: edge
language: cpp

env:
  global:
  - coverity_scan_script_test_mode=false
  - coverity_scan_run_condition='"$TRAVIS_OS_NAME" != osx -a "$BUILD_TYPE" = Release'
  - secure: s8DdaxdWVR3qRBxfxO6UjugB1dWlEnv9KhF1ZUHDhWziPtoecKjCXnJYSB6EOddTPoJXtOdTVW9ThGGCvKQ+vYdGNce+PCWglruANO/lEz/82HWPZkTKbw4WyoDo5GqlFCu1C3gY9dA58ClpGDlX5BNQA81JCJrWKUdR2J0/WW9USPKHxDLGISYKt28nwVjywR8uDnysBJkmmS+53Ge2MSzmOLuEZeysq7iCD6xssPL5UDDb/itNOc4OkvRGtvTnLrMF4c7naFRfbhc7NR1MxKz+eu2DgM9SAnJrh1jnYXWu/1EG8VKQOYR23OwjxSurSRjJxInGZdrSGUB8R38Z35Ndq7RHKRAZvwIPkZqDFCUQ/hkAJlu/4cbz8KPHJMOV0SOFpCztnFCQY619KXn0S0Tos38KthVu2nNSMJu1e1GuQK1dhM+Uh3MCrSChyPmK75IKbM7Jj5OKRqKO4uSnsut3RK91RYF3oB3HdLkznTLYBLnyEWK6Zh56lhoZiJMd/WCL24/U5Pne6VwLDBjaeOH9lEjD6oaUSIDyowVAOte4qVg7WW7OXx2fkK9ySd4X0P5C5JLtWsZ8O+va9LkIxPPCdck3HV+k1EU0tHrLAAkpwO3D9StRdkc7cX+z13aFOZQyKef1wbKyNCYrq6E3SGvlI011+0vN2ZiGKKusGcs=
  - secure: JuSus/BqBJ2RTj7oJ3tn6dfFqnNWmWdM6/+PBId8YT52fUJTQp0eLmYbqZhq04OFvCKLgzeiObggfFZk5VOXAB/bfhlQEKSprso6C0WxKzFnftr085rcr5mW2ux+RSWTeE9KT1bpsjtpSrQTOniQhPGD6u704DdIzKuOnSngU8TXRAHFujXtUA0SHU8Oft8OpysaTDVWbFehBemg6BeOssklw2LrScGT3AWm8+qNdyAV+ynko4s8CzdOJqueCNWnkYFQyNtWN67uasveg3j+zgOfstjgyYSEoYh6deCNy8BjmWzX2tUkpzxh7h4w/VlyVjvyMG524UdMDmFZNNo7CMn1/qla6zjli3xDV/kk2Dfzj1JCn2WsesOY8+p4bdYoUU4lR0PuYraEuBAOCiVb3V7VLzU5FyV3clY8+MwifVHvNLxUbyD2ygZfPrS8LQJ/7jJSPeEARUIngvNkY9L8Jr6olw3Xg7DoDHLWAFBMtBi/sZG3CvXDyeIUX8rkh4hY6QlnO/xrql5KxDupsAwqj+rMdhzYeCnyRY6HvqBIoIrpi47uPGutxiIFgjrzwr28eL+XrrkwHfbM+pFDUITdWjm79/EyEPgGsEMM8IxXcpSGNmMDDhpHu1oZE4L3gdKli6hdS5fo6CEDV3x1nvk/SsY52WhEWIT/RwQPl4qL3YQ=
  - secure: tvFQn4BjO/DG0yE5NEdZsmY73qsxhN5CsXl+C4GkCzz8KgtOGyVFij5R18+IP3X44CKOz54dLy9pE3lCY2v9wvvLnnv1hV3kH2EvV5Ccv2zw8jozz7OpxK2GMSoqPvHK/FAEo3mbuwhnOS2fEV3+hWSF9/piwSAmFhnjH7VHZnnx8yVfpzEl0Oq4JLM1fEx400Z+Glvn9uDfjY8cvzRVp8HqHTuPNNRLmNvGPAYqstpKAxEh6Tml6eUrCxbndbcvtTt7vlshW9OuU5LVh2Y63ftZpsKCWfpu5K4MfgD4oLineo+2zz3jfv/Hs8vTVLzRQph6OkxLiZBqUgUyoZzZ/r4bMQbbS6wmbWwZOaIQyjFRr68FZ/yW4JJ/KkUhMB3LA7it2rNhhI6+jTQqvLO+VAucuUmFJ0xIsbULBTo7cyL7X40rDLFxhXNLTjcqPT1nUzKCrmFxrDh7utegggN0UtXVAWl6KN8f003TVlunM+BrB8r08kX/JU0modFzXS0sMDF/tuzMd9dd/R4CtoHAuP20J7LZ81EA8IbKJ5j6dsc8l+Ti5/LwLrEtxXnD6MSSNDoSZszeyLA78+zGzKLNNvHGdnHTFgFd3Q/gVYJgH6AWAVCJeSnwXbI78azIFohPwsT/JsJS092Ck6rgRKpbZNNmOVfpn6WsXoQBrLpcg0A=
  # start artifacts
  - ARTIFACTS_BUCKET=osirose-builds
  - secure: "tDTFSzBd6ASR8BM/pZMLMQy1jjlbxA81WaLfZ70OgTZE6KZ+X+mSdu/i5SyXzhdZSl62tVDo2jIjGupGLtzWjMtRJiN2zNHscYS+V4BbSfk97zKXs+fH96aDlGJBIqJSxT3aRqgvTCLFXzEWyZEQxzYX7u9I5P0ftMBOalkxfcU1JrBerJBdsXLFuGjKfyGfCOzvRBCjzpAhKHTsD4ecJyqqTk3XqDqE4P+8ibJXw0fWj6D0K2XTNq4krol+Vmcw2qZEGp3gVAy6blOM1ggopFRr/gTZjyA6Q/twnS07DH7w1v2RnCMjc12rTlR8usVrHYo73FUO47PMuWy/UhOhziuJy9Zu6GxcenRS/JmVYVY3cDcuczkrHX4JIn/qtwNROd8vhos+rOMFv04KsZYOkILrJmSmrwELldTw1/VkKMuk7rjcS+lcGbm2K+XZ9xUXefNGNnYbWlpQ6v8anAgOFU0/eOY3y2PknhH/2tUxX+hHq1AFMv63cGkSoRLPSXKz8gdKKN1dEIb8/ZLrz5glvv6rsLRqfvO6K3U1jyM5Sb2YCpIRd2x8CEv09QwVHWVjXdmBSVURdfY3p41G16wvMT3GCH7/VCJ6rGz1WmFzMEDX2ua5P+SFXagL0iBZNmF1HWVxkpwE1MGPkq/WlpSw//cY+2PNBktDjClluzE3w9s="
  - secure: "CgXInxIv08nvVBQY9UgP9ZeBMlDyuQ9wr0DmoB61UGMGNaJps11Shuikz0tDcJxqFsSapJPkXc03B6rK7Bhckdz3MKYp0RLNsEv0984QkKiseYnqFc6h6qJGV2AgsbHLBKZoqxVxeDV2biKvYqDkG3ylTSSaL7+eMvTguc2aK9zUhcFKoBdsRBECTdte2Nd/GVUIJIuUaFMncuTscZLR5VwNaN8xf6BTG5oitKbBje304/soMgHL9WdGuzeBT42QtE8yJ82SmlPvV/dAjGaSwLENmehpc3XIlaevrJg4Ptti8XBazjwvCR9bF5HVnP5uADqmLcznl1PQXDLjNeVryLjnFvAf4wveLxHeW13olMnZsgV84ABWEHTcUuz4z5KM+BKvLGjQB3R9msVr2YKn0KJfqeCPSdnctKAgKlYyRFKOIuohuHsVu+PJzq6NOFWs6c3IrEE+YgqSXhpgFcARt/Z1BTfVm9sAlHEY5I9Hlzxfl+F9HvjvQXtzhwt3fMB6dCeQfnGp/k660Q4wpo7zWHPc7o2OskeZwrTKzaSovFYXltGRQxDKOPZEjA1aLpK8Dnk46x+p9Kd+ClsV+WeOOG+u3xjR90NIjhOziurtMgMy/m/XluIvbMDCChZF8ecvo5+qEWeB9fAp3dSrkn4xInbTG+747P3hL2FxRLflwdo="
  # other artifacts upload
  - secure: "xBpVz5i5Cr2E47irPh4tbe4ytOAxIEN3vz68h0xDjRrFg+ZhYNarZsjTAHOgZuGyzMhoDmI3Ld8VvI5Qqx00giK+zkJ2SSqDx2UvAvn6cE8+Td9GyQ9wM8yNysU96l+mHpxwhDUabin6DG0Ea9XO4Qzc2qtWURkZxvymmzH5mEpklp8LoBjrr42e3Mo3J0h4C94wO/y6TenjjP8r0y2spUakxTC84u1T11zysKm/C16w3GECDNqaTMVO7zi9ctVjsTBPSqTA9PwuecUfMnB0B4f906U6B45xlVT0fXu76gEed7EeB8/YUHXU68BaTxP9pM9ytxiWZ6Wb+WPIPHS5cp4JuB7JTv4vmBlznBZdFkijhiQmoSloVtWhF6lBh0ke6ecP3/Wp0xuR4Qf+BdkbH9m13JzkDXKIeYnDbIJZ2XSCgo/Z7DQ23Xa2KB3SEvXT1LCbaZOwtxVxEVLBwlcYtH34CTmdG8gSvso4ZM4q6hSjTWjcXRY7zmgkJLRjtdPA+yaWmyXfYKz50CJ5QTmJj65LglIO3GszaEVvRwdy35SDiiEhnF8XNKJ5lFYTNgaGzY+o0gL0ZE1fAHI6GahBiY5a+9r2vHvMQ9QIOei3Ny1w2dZ/8ATZyZbXXjBmBLIwf0iY36pXzbTpRgZQi2fe0nGl2lg11Il4rtfyBL5hQfs="
  - secure: "HuHas8zjvhptDPYZtq8bq2Zp54iqlZ5vuVZx859fPr42nqn9UoGWUlAhBlT7MDb9zPPGTtkHPRgoH85jTqxEKt+XmC4IvPkTch64N45G8qE06Kp+wKjzDyrSWn9OiMkk/Dfx/ppALBKmOGWNYoAHVSs1uM/iW3lniCXGAjKawf6eTZ56rQu59dLki723hugVFnLHou2lv/aAqAjJF4BydnHPHGZWthegjo2NDSaTJs3jtxTAMvYoUTPFVXumfNfS8/NlCFY5//YPOtVpTlHdfI8xmr89CuRdy/tuti7Dhbll+GVeRmFfUwSIREFp9mUZDiaDk3df1KBdND1pmmDEdEGZ0O3sKNpXGfHKAGxcHfKAPgSowlcRRPuqnZVcOfVtwgJOR+0JhV/WuUqZMqkHArYhHnudvojZ5euTAKKNdxrn8hYHw+jpHkHvCHmt+4KA4TR/OhoW6fxSKQNkcpTc4eREt53FoKOWhF3zJNx+YM/8/E07mu3j7zxbZHDspNtD5HrfU36WfxprAj62uvujKaqfhYjKBjq/k0THAcUPpQ8KoH75zjUMtn0k2sVpUlumci/1JErLipBtAWyOWwhcbFgMzX7I0UqbMuZ3mOivvjjX+3m6tntR2FReh8CUoh8dfhOsoAp3Fgm8mskuJLQ0/ry+YXe4+tIKyAHYu6Qhibk="
  - secure: "rhEt4Tgu1txNXU//wxmxZCTiIbFeZMZpCWUt5kmQDJN8pn1Phykr1cdoHG9uMQ0BYmo+aGyt/IdFlNiPP5LWNHYTMRj0SlQu2RsYQzQqAkQ6ZbKdWOcBddeDZehSwiDNllIx7qMcpjrqeKdsf6NyEzlhp+Zb9wkfS0ghpWa2OhXMMxLmVSZngWQByh+SzCdkuuDXNXJZdDUh9bKovowvngW+AyqMpn1lJzC671zX8o/f2reedHp/SbEvz0DIHNK6euWC7Qr1BhkOGxuaBtNvbtbtyCzpsc+NoWRbYFhlsEVvkA3jSD7bqOpda1/cqfbGRVTk/vUU+I5n02gpC5rqvX65aLtsGWeWYFvuxVHPqE5UAgMk0+6WdSEWotBhjnrGN3U8zNKG9TxrTIHn24EUVMDmGNcxujtoFpEeUrU8gp5TCKb4rwi0S722YhcnkKqZuPcQ8GMdr0sme+C5zWQev+6UuUpW1UJnrBDTMDgK/vScRU4l6WGB7Gkvxyd+yxwoCEe8l3WKBbNv0v1TcKqnoYIDiIhSkWMHtOQBC7b88bJI/uiKNZ2qEakiNlcuuVkCow1nC0jlJTSiOlzDRdS5sWYlTS7TaKqwSrnN7SR3SMWO10hw18ACY1wbwGk9BTwaLSX625Dm54OJI8AtWjrI0ASvrkd/B3INLww7UYO8xdQ="
  # end artifacts
  - SUITE=tests
  - PREFIX=${TRAVIS_BUILD_DIR}/3rdparty
  - PROOT=echo "ERRROOORRRR STILL USING PROOT!@!@!@!@!@"
  - WITH_CRASH_REPORTS=ON
  - BUILD_JOB_COUNT=4
  - PATH=${TRAVIS_BUILD_DIR}/3rdparty/bin:${TRAVIS_BUILD_DIR}/3rdparty/usr/bin:${TRAVIS_BUILD_DIR}/3rdparty/usr/local/bin:${TRAVIS_BUILD_DIR}/cmake_app/bin:${TRAVIS_BUILD_DIR}/ninja:$HOME/usr/bin:$HOME/usr/local/bin:$PATH
  - LCOV_PATH=${TRAVIS_BUILD_DIR}/3rdparty/usr/local/bin/lcov
  - CI_DIRECTORY=${TRAVIS_BUILD_DIR}/cmake/scripts
  - GENHTML_PATH=${TRAVIS_BUILD_DIR}/3rdparty/usr/local/bin/genhtml
  
services:
  mysql

cache:
  pip: true
  ccache: true
  bundler: true
  directories:
  - ${TRAVIS_BUILD_DIR}/3rdparty/bin
  - ${TRAVIS_BUILD_DIR}/3rdparty/lib
  - ${TRAVIS_BUILD_DIR}/3rdparty/include
  - ${TRAVIS_BUILD_DIR}/ninja

jobs:
  include:
    - &gccinit
      stage: prepare cache
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      compiler: g++
      addons:
        apt:
          sources:
          - deadsnakes
          - ubuntu-toolchain-r-test
          packages:
          - lcov
          - g++-7
      before_install:
        - eval "${MATRIX_EVAL}"
        - export PREFIX=${TRAVIS_BUILD_DIR}/3rdparty
        - export PATH=${TRAVIS_BUILD_DIR}/3rdparty/bin:$PATH
      install:
        ############################################################################
        # Install a recent CMake
        ############################################################################
        - |
          if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
            mkdir cmake_app && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/cmake_app
          else
            brew upgrade cmake || brew install cmake
          fi
        - cmake --version
        - bash $CI_DIRECTORY/install-ccache.sh
        - ccache --version
        - ccache --show-stats
        - bash $CI_DIRECTORY/install-lcov.sh
        - bash $CI_DIRECTORY/install-ninja.sh
        - bash $CI_DIRECTORY/install-mysql.sh
      script: true
      
    - &clanginit
      stage: prepare cache
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      compiler: clang++
      addons:
        apt:
          sources:
          - deadsnakes
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
          packages:
          - lcov
          - g++-7
          - clang-5.0
      before_install:
        - eval "${MATRIX_EVAL}"
        - export PREFIX=${TRAVIS_BUILD_DIR}/3rdparty
        - export PATH=${TRAVIS_BUILD_DIR}/3rdparty/bin:$PATH
      install:
        ############################################################################
        # Install a recent CMake
        ############################################################################
        - |
          if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
            mkdir cmake_app && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/cmake_app
          else
            brew upgrade cmake || brew install cmake
          fi
        - cmake --version
        - bash $CI_DIRECTORY/install-ccache.sh
        - ccache --version
        - ccache --show-stats
        - bash $CI_DIRECTORY/install-lcov.sh
        - bash $CI_DIRECTORY/install-ninja.sh
        - bash $CI_DIRECTORY/install-mysql.sh
      script: true
      
    - <<: *gccinit
      stage: compile
      if: branch != coverity_scan
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" SUITE=tests BUILD_TYPE=Debug
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - export CC=gcc-7 CXX=g++-7
        - export GCOV_EXEC=gcov-7
        - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
        - mysql --user="root" -e 'create database osirose;'
        - mysql --user="root" --database="osirose" --password="" < "$TRAVIS_BUILD_DIR/Database/osirose.sql"
        - bash $CI_DIRECTORY/before_script.sh
      script: 
        - cd build
        - cmake -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DWITH_CRASH_REPORTS=${WITH_CRASH_REPORTS} ..
        - cmake --build . -- -j ${BUILD_JOB_COUNT}
      after_script:
        - ccache --version
        - ccache --show-stats
        - ctest --output-on-failure
    
    - <<: *gccinit
      stage: compile
      if: branch != coverity_scan
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" SUITE=coverage BUILD_TYPE=Release
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - export CC=gcc-7 CXX=g++-7
        - export GCOV_EXEC=gcov-7
        - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
        - mysql --user="root" -e 'create database osirose;'
        - mysql --user="root" --database="osirose" --password="" < "$TRAVIS_BUILD_DIR/Database/osirose.sql"
        - bash $CI_DIRECTORY/before_script.sh
      script:
        - cd build
        - cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DWITH_CRASH_REPORTS=${WITH_CRASH_REPORTS} -DWITH_COVERAGE_REPORTS=ON ..
        - cmake --build . -- -j ${BUILD_JOB_COUNT}
      after_script:
        - ccache --version
        - ccache --show-stats
        - cmake --build . --target coverage
        - coveralls-lcov coverage.info.cleaned
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
      after_success:
        - mkdir ${TRAVIS_BUILD_DIR}/public
        - tar -czvf ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz ${TRAVIS_BUILD_DIR}/build/bin
        - curl --ftp-create-dirs -T ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_HOST/${TRAVIS_OS_NAME}/${BUILD_TYPE}/${TRAVIS_OS_NAME}-${BUILD_TYPE}.tar.gz
      
    - <<: *clanginit
      stage: compile
      if: branch != coverity_scan
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" SUITE=tests BUILD_TYPE=Debug
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - export CC=clang-5.0 CXX=clang++-5.0
        - export GCOV_PATH=$CI_DIRECTORY/llvm-gcov.sh
        - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
        - mysql --user="root" -e 'create database osirose;'
        - mysql --user="root" --database="osirose" --password="" < "$TRAVIS_BUILD_DIR/Database/osirose.sql"
        - bash $CI_DIRECTORY/before_script.sh
      script:
        - cd build
        - cmake -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DWITH_CRASH_REPORTS=${WITH_CRASH_REPORTS} -DWITH_COVERAGE_REPORTS=ON ..
        - cmake --build . -- -j ${BUILD_JOB_COUNT}
      after_script:
        - ccache --version
        - ccache --show-stats
        - ctest --output-on-failure
      
    - <<: *clanginit
      stage: compile
      if: branch != coverity_scan
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" SUITE=tests BUILD_TYPE=Release
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - export CC=clang-5.0 CXX=clang++-5.0
        - export GCOV_PATH=$CI_DIRECTORY/llvm-gcov.sh
        - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
        - mysql --user="root" -e 'create database osirose;'
        - mysql --user="root" --database="osirose" --password="" < "$TRAVIS_BUILD_DIR/Database/osirose.sql"
        - bash $CI_DIRECTORY/before_script.sh
      script:
        - cd build
        - cmake -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DWITH_CRASH_REPORTS=${WITH_CRASH_REPORTS} -DWITH_COVERAGE_REPORTS=ON ..
        - cmake --build . -- -j ${BUILD_JOB_COUNT}
      after_script:
        - ccache --version
        - ccache --show-stats
        - ctest --output-on-failure
      
    - <<: *gccinit
      stage: compile
      if: branch = coverity_scan
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - export CC=gcc-7 CXX=g++-7
        - export GCOV_EXEC=gcov-7
      script: true
      addons:
        coverity_scan:
          build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis-coverity-scan-build.sh
          project:
            name: "$TRAVIS_REPO_SLUG"
          build_command_prepend: cov-configure --comptype gcc --compiler gcc-7 --template;
            cov-configure --comptype gcc --compiler cmake --template; mkdir build; cd build;
            cmake -DOFFICIAL_BUILD=ON -DWITH_CRASH_REPORTS=OFF ..;
          build_command: cmake --build . -- -j ${BUILD_JOB_COUNT}
          branch_pattern: coverity_scan
          
    - <<: *gccinit
      stage: testing
      if: branch != coverity_scan
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" SUITE=coverage BUILD_TYPE=Release
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - export GCOV_EXEC=gcov-7
        - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
        - mysql --user="root" -e 'create database osirose;'
        - mysql --user="root" --database="osirose" --password="" < "$TRAVIS_BUILD_DIR/Database/osirose.sql"
        - curl -O -u $FTP_USER:$FTP_PASSWORD --remote-name $FTP_HOST/${TRAVIS_OS_NAME}/${BUILD_TYPE}/${TRAVIS_OS_NAME}-${BUILD_TYPE}.tar.gz
      script:
        - tar -xf ${TRAVIS_OS_NAME}-${BUILD_TYPE}.tar.gz
        - cd build
        - ${LCOV_PATH} --directory . --zerocounters
        - ${LCOV_PATH} -c -i -d . -o coverage.base
        - ./bin/TestConfig
        - ./bin/TestConsole
        - ./bin/TestMySQLDB
        - ./bin/TestASIONetwork
        - ./bin/TestRoseCrypt
        - ./bin/TestRoseNetwork
        - ./bin/TestLoginServer
        - ./bin/TestCharServer
        - ./bin/TestAllServers
        - ./bin/TestRosePackets
        - ./bin/TestSystems
        - ${LCOV_PATH} --directory . --capture --output-file coverage.info
        - ${LCOV_PATH} -a coverage.base -a coverage.info --output-file coverage.total
        - ${LCOV_PATH} --remove coverage.total 'tests/*' '/usr/*' '3rdparty' --output-file coverage.info.cleaned
        - ${GENHTML_PATH} -o coverage coverage.info.cleaned
        - coveralls-lcov coverage.info.cleaned
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
        - rm coverage.base coverage.total coverage.info.cleaned

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0363885535a5495e8f8f
    on_success: change
    on_failure: always
    on_start: never
  slack:
    secure: KHU2ZMzBGGtsaWF7wylutlLPAxCEZD2/NQQbmbaEpsaWSitXnO9XOLRLsLJP6QGLOgiDHHmGcRiO7wgmbsvP79zRaChs/LLfUY2F5laXgpZdL9OI/z8zygeY1iSZSNMMr0MCYf7TilRvOqTSFpB7RcuQ65G1ZGow8h6MunU5WaSyjC7REOJcSmL3IQ08Zcf8oZgdd6EqogSW1Eubcp4IhlsiQQTLdzeAQWwkfJ8DDO1gPC8bWdJCBg9hMUub5K/UQHEOY8KmH1KTOk/FedjI8wTWD+0m8SjFJq8wUs9ieQyGikZbK6F8WmjZdG0GLRWb7POxIOQjqxi2/ZRUMTHvDr5s+0BUQmKYUwkc/oUf/Bg/eYnU/LjM7prnQU08ZPGDwoh5L/alZM4eGKez3KFb4Co3e7HSI+FN9mQFKcgjnMOJIE1kaw1V+9Uj1DJemWi6voKmApJ3s8U44FduI30fpAD0FQQw8dEfF2Iug3O093KdPy0aEySOZ44a0VYD5iB7Dc129xumwOd5EAvGXHc+3/Wf0TLsskct2IlNVv6DaKkstk0YXjz7PkhkMJEAvYYi/ANQ8h/Ixh7Xnj7bcX+boBazIM6V+U6sxysQUsvWihXpxtqs+N7Z0eiRbC7s4TAMX1hVVvoERlLRVOTCl+QsRemTgt1QXV0rMl78h8xg8lg=

#after_success:
#  - mkdir ${TRAVIS_BUILD_DIR}/public
#  - tar -czvf ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz ${TRAVIS_BUILD_DIR}/build/bin ${TRAVIS_BUILD_DIR}/build/lib ${TRAVIS_BUILD_DIR}/Database
##  - curl --ftp-create-dirs -T ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_HOST/success/
#  
after_failure:
  - mkdir ${TRAVIS_BUILD_DIR}/public
  - tar -czvf ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz ${TRAVIS_BUILD_DIR}/3rdparty ${TRAVIS_BUILD_DIR}/build ${TRAVIS_BUILD_DIR}/src ${TRAVIS_BUILD_DIR}/Database /tmp/dumps
  - curl --ftp-create-dirs -T ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_HOST/failure/

deploy:
  - provider: releases
    api_key:
      secure: "BeGzqO3xstU53ChZHaEd0tx94UnOFE8mhD/47jLlBWy2MM1pxFfI9zYSfGaBAa0FBY4SjSxPyA8ChZcoHWVxSv0j59LxhI+sOyTS5Rak3UT1Nlm3WqmvRIEx5E9kuF4Z28nXQuJYPvMqdXwx7F4Qk2wRLuQHmrvllwnuEJouelR54EiAcF6h5Gk7G1j8Yvpn7kyJIJL8+a3zwEt8u4UEw8S9R4akti6EINmyYbKldVny4i8uzSas1fjeJmZlXLGvykjlcGFl4X5OEmShowRcHNjhyK7Awprbycbf7rV2es0V/UFIr+xYX/6z7sdtGiXpoBYTQksilE3IcYAt5WcvgxPnSgG12njcTHjhX+MQFW+bbYWr21OA9DQn+KfRMTI00DB3huv1KCFh5IawSjijY9j8scijMofb58vYj960yUJfoOnZeicp3raM4/eVRKCtEdk7UwWNLqqB3o1Cfug8ZohhSbUHeGUQfyCBtYWSrE6/xb5mQmOUQI54ocSUKcmvv59G58nZic0Nl29cj9aYyu1lc093gSxnQ9cCtwbNkKCHiA+Z5MGScJ5jwydylckzeQysUzOK/ISFU4O0vX48GhSBOb3D6O9K4AoVG43vBu9E895tktDuj0BQ4uvtT7fN8xDJc6vg2uAEQst0yfWJZ/qDzKJIEoFYnvbMQh0JCwA="
    file: ${TRAVIS_BUILD_DIR}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: $CXX = "g++-7" && $BUILD_TYPE = "Release"
      tags: true
