version: '{branch}-ci-{build}'
os:
- Visual Studio 2015 

configuration:
- Debug
- Release

platform:
- Win32

environment:
  ASIO_STANDALONE: 1
  MYSQL_DATABASE: osirose
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PWD: "Password12!"
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  MYSQL_CONNECTOR_PATH: C:\Program Files (x86)\MySQL\MySQL Connector C 6.1
  PROJECT_PATH: C:\projects\osIROSE
  GTEST_OUTPUT: C:\projects\osIROSE\build\Test.xml
  PYTHON_PATH: C:\Python35
  INCLUDE: C:\projects\osIROSE\tools\googletest\googlemock\include;C:\projects\osIROSE\tools\googletest\googletest\include;C:\projects\osIROSE\tools\spdlog\include;C:\projects\osIROSE\tools\pbjson\src;
  
matrix:
  fast_finish: true
  
clone_depth: 50
clone_folder: C:\projects\osIROSE
services: mysql

install:
- cmd: cd %PROJECT_PATH%
- ps: Start-FileDownload http://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-win32.msi -FileName C:\projects\osIROSE\mysql-connector-c-6.1.6-winx32.msi
- cmd: git submodule update --init --recursive
- cmd: "./ci/msvc_mysqlpp_install.bat"
- cmd: "./ci/msvc_install.bat"

#cache: 
#- %PROJECT_PATH%\3rdParty -> clear_cache.txt
#- %PROJECT_PATH%\build\tools\protobuf -> clear_cache.txt
build:
  parallel: true
  
build_script:
- cd build
- cmake -DBUILD_TYPE=%CONFIGURATION% -DBUILD_MYSQLPP=ON -DBUILD_PROTOBUF=ON -Dprotobuf_BUILD_TESTS=OFF -DENABLE_TESTING=ON ..
- cmake --build . --config %CONFIGURATION% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: build/bin
  name: build-bin
- path: build/lib
  name: build-lib
  
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: QRzsk64PSFoDEGoTiL44n9yIlkyCrY/cG2HW5hVDIlVNdkW/m47qgyjTeBR4ri5+PmYwVxelkdOipzJBeTVRSsciTo2aGnk4QHXyRyR4Nra6SAxaDuKFUC3Sbc8jXnmq
  channel: osirose-commits
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
  
before_test:
  - SET PATH=%MYSQL_CONNECTOR_PATH%\lib;%MYSQL_PATH%\bin;%PYTHON_PATH%\Scripts;%PATH%
  - SET STATIC_DEPS=true
  - pip.exe install lxml
  - cp "%MYSQL_CONNECTOR_PATH%\lib\libmysql.dll" "%PROJECT_PATH%\build\bin\%CONFIGURATION%"
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PWD% create %MYSQL_DATABASE%
  - mysql --user=%MYSQL_USER% --password=%MYSQL_PWD% --database=%MYSQL_DATABASE% < "%PROJECT_PATH%/Database/osirose.sql"
  - C:/projects/osIROSE/build/bin/%CONFIGURATION%/osirose-tests.exe --gtest_filter=SetupTesting.**
  - ps: $a = Get-Content 'C:\projects\osIROSE\build\server.ini' -raw | ConvertFrom-Json; $a.database | % {if($_.user -eq 'root'){$_.password='Password12!'}}; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\server.ini'; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\test.ini'; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\src\tests\server.ini'; $a | ConvertTo-Json  | set-content 'C:\projects\osIROSE\build\src\tests\test.ini';
  
test_script:
  - ctest -C %CONFIGURATION% --no-compress-output -T Test -E "TestConfig|SetupTesting" || verify > NUL
  - ps: $xml = cmd /c "C:\Python35\python" C:/projects/osIROSE/ci/convert.py -t C:/projects/osIROSE/build -x C:/projects/osIROSE/ci/conv.xsl 2`>`&1; $xml | Out-File C:/projects/osIROSE/build/results.xml; $wc = New-Object 'System.Net.WebClient'; $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path C:/projects/osIROSE/build/results.xml));

  
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
