version: 1.0.{build}
os:
- Visual Studio 2013
- Windows Server 2012 R2
- MinGW
configuration:
- Debug
- Release
platform:
- Win32
environment:
  ASIO_STANDALONE: 1
clone_depth: 50
clone_folder: C:\projects\osIROSE
services: mysql56
install:
- ps: If( (Test-Path C:\projects\osIROSE\3rdParty) -eq $false ) { Start-FileDownload https://www.dropbox.com/s/6if9vlf54xy7lqg/3rdParty.zip?raw=1 -FileName C:\projects\3rdParty.zip }
- cmd: IF NOT EXIST "C:\projects\osIROSE\3rdParty" "7z x C:\projects\3rdParty.zip -oC:\projects\osIROSE\ -y > nul"
- cmd: git submodule update --init --recursive
cache: C:\projects\osIROSE\3rdParty
build:
  project: osIROSE.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin
  name: build-bin
- path: lib
  name: build-lib
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: QRzsk64PSFoDEGoTiL44n9yIlkyCrY/cG2HW5hVDIlVNdkW/m47qgyjTeBR4ri5+PmYwVxelkdOipzJBeTVRSsciTo2aGnk4QHXyRyR4Nra6SAxaDuKFUC3Sbc8jXnmq
  channel: osirose-commits
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
